from database import engine, SessionLocal, Base

from models import Record

Base.metadata.create_all(bind=engine)

db = SessionLocal()

new_users = [
    {"name": "Simeon",
    "gender": "Male",
    "date_of_birth": "10/04/36",
    "occupation": "Ai Developer",
    "state_of_origin": "Ogun State"},
    {"name": "Simeon",
    "gender": "Male",
    "date_of_birth": "10/04/36",
    "occupation": "Ai Developer",
    "state_of_origin": "Ogun State"},
    {"name": "Simeon",
    "gender": "Male",
    "date_of_birth": "10/04/36",
    "occupation": "Ai Developer",
    "state_of_origin": "Ogun State"},
    {"name": "Simeon",
    "gender": "Male",
    "date_of_birth": "10/04/36",
    "occupation": "Ai Developer",
    "state_of_origin": "Ogun State"},
    {"name": "Simeon",
    "gender": "Male",
    "date_of_birth": "10/04/36",
    "occupation": "Ai Developer",
    "state_of_origin": "Ogun State"},
    {"name": "Simeon",
    "gender": "Male",
    "date_of_birth": "10/04/36",
    "occupation": "Ai Developer",
    "state_of_origin": "Ogun State"},
    {"name": "Simeon",
    "gender": "Male",
    "date_of_birth": "10/04/36",
    "occupation": "Ai Developer",
    "state_of_origin": "Ogun State"},
    {"name": "Simeon",
    "gender": "Male",
    "date_of_birth": "10/04/36",
    "occupation": "Ai Developer",
    "state_of_origin": "Ogun State"},
    {"name": "Simeon",
    "gender": "Male",
    "date_of_birth": "10/04/36",
    "occupation": "Ai Developer",
    "state_of_origin": "Ogun State"},
    {"name": "Simeon",
    "gender": "Male",
    "date_of_birth": "10/04/36",
    "occupation": "Ai Developer",
    "state_of_origin": "Ogun State"},
    {"name": "Simeon",
    "gender": "Male",
    "date_of_birth": "10/04/36",
    "occupation": "Ai Developer",
    "state_of_origin": "Ogun State"},
    {"name": "Simeon",
    "gender": "Male",
    "date_of_birth": "10/04/36",
    "occupation": "Ai Developer",
    "state_of_origin": "Ogun State"},
    {"name": "Simeon",
    "gender": "Male",
    "date_of_birth": "10/04/36",
    "occupation": "Ai Developer",
    "state_of_origin": "Ogun State"},
    {"name": "Simeon",
    "gender": "Male",
    "date_of_birth": "10/04/36",
    "occupation": "Ai Developer",
    "state_of_origin": "Ogun State"},
    {"name": "Simeon",
    "gender": "Male",
    "date_of_birth": "10/04/36",
    "occupation": "Ai Developer",
    "state_of_origin": "Ogun State"},
    {"name": "Simeon",
    "gender": "Male",
    "date_of_birth": "10/04/36",
    "occupation": "Ai Developer",
    "state_of_origin": "Ogun State"},
    {"name": "Simeon",
    "gender": "Male",
    "date_of_birth": "10/04/36",
    "occupation": "Ai Developer",
    "state_of_origin": "Ogun State"},
    {"name": "Simeon",
    "gender": "Male",
    "date_of_birth": "10/04/36",
    "occupation": "Ai Developer",
    "state_of_origin": "Ogun State"}
]

for user in new_users:
    db.add(Record(**user))

db.commit()
db.close()